/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantorderprocessor.UI;

/**
 * Form component for Customer Details
 * @author stephenfleming & kosta
 */
public class CustomerDetails extends javax.swing.JPanel {

    /**
     * Creates new form CustomerDetails
     */
    public CustomerDetails() {
        initComponents();
    }
    /**
     * Resets the CustomerDetails input options to their default blank states
     */
    public void resetCustomerOptions()
    {
        //Reset Customer name
        fieldCustomerName.setText("");
        //Reset Table Number
        fieldTableNumber.setText("");
        //Reset all radio buttons
        radioBreakfast.setSelected(false);
        radioDinner.setSelected(false);
        radioLunch.setSelected(false);
    }
    /**
     * Getter for Customer Name
     * @return fieldCustomerName text as string
     */
    public String getCustomerName() {
        return fieldCustomerName.getText();
    }
    /**
     * Getter for Table Number
     * @return fieldTableNumber text as string
     */
    public String getTableNumber() {
        return fieldTableNumber.getText();
    }
    /**
     * Getter for meal type selected
     * @return meal type as string
     */
    public String getMenuType() {
        if (radioBreakfast.isSelected())
            return "BreakFast";
        if (radioDinner.isSelected())
            return "Dinner";
        if (radioLunch.isSelected())
            return "Lunch";
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        options = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        fieldCustomerName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldTableNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        radioBreakfast = new javax.swing.JRadioButton();
        radioLunch = new javax.swing.JRadioButton();
        radioDinner = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jRadioButton1.setText("jRadioButton1");

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Customer Name: ");

        fieldCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCustomerNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Table Number:");

        jLabel3.setText("Menu Items: ");

        options.add(radioBreakfast);
        radioBreakfast.setText("Breakfast");

        options.add(radioLunch);
        radioLunch.setText("Lunch");

        options.add(radioDinner);
        radioDinner.setText("Dinner");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldCustomerName, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldTableNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioBreakfast)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioLunch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioDinner))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(fieldTableNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(radioBreakfast)
                    .addComponent(radioLunch)
                    .addComponent(radioDinner))
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCustomerNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldCustomerName;
    private javax.swing.JTextField fieldTableNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.ButtonGroup options;
    private javax.swing.JRadioButton radioBreakfast;
    private javax.swing.JRadioButton radioDinner;
    private javax.swing.JRadioButton radioLunch;
    // End of variables declaration//GEN-END:variables
}
