/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prototypeclientserver.ClientCustomer;

import javax.swing.*;
import java.awt.BorderLayout;
import java.awt.Panel;
import java.awt.event.ActionListener;
import java.awt.event.FocusListener;
import prototypeclientserver.Order;
import prototypeclientserver.components.NutritionalInfoTable;

/**
 * 
 */
public class ClientScreenView extends javax.swing.JFrame {

    /**
     * Creates new form ClientScreenView
     */
    public ClientScreenView() {
        initComponents();
    }
    /**
     * Adds an ActionListener for Enter Data button
     * @param l ActionListener to add
     */    
    public void addEnterDataListener(ActionListener l)
    {
        buttonEnterData.addActionListener(l);
    }
    /**
     * Adds an ActionListener for Display Choice button
     * @param l ActionListener to add
     */    
    public void addDisplayChoiceListener(ActionListener l)
    {
        buttonDisplayChoices.addActionListener(l);
    }
    /**
     * Adds a FocusListener for Display Order button
     * @param f FocusListener to add
     */    
    public void addDisplayOrderListener(FocusListener f)
    {
        buttonDisplayOrder.addFocusListener(f);
    }
    
    public void addContentToOutputPanel(JPanel content) {
        outputPanelEmpty.removeAll();
        
        Panel p2 = new Panel();
        p2.setLayout(new BorderLayout());
        p2.add(content);
        
        outputPanelEmpty.add(p2);
        
        outputPanelEmpty.updateUI();
        pack();
    }
    
    public CustomerDetails getCustomerDetails() {
        return customerDetails;
    }
    
    public MenuItems getMenuItems() {
        return menuItems;
    }
    
     /**
     * Displays a pop-up message to the JFrame
     * @param msg String message to display
     */
    public void displayPopup(String msg) {
        //src: https://stackoverflow.com/questions/9119481/how-to-present-a-simple-alert-message-in-java
        JOptionPane.showMessageDialog(null, msg);
        //end src
    }
    
    /**
     * Updates the Output Order Table with new row
     * Clears the previous configuration of rows
     * Then adds the new specified row
     * @param ord Order to add
     */
    public void updateOutputOrderTable(Order order)
    {
        NutritionalInfoTable table = new NutritionalInfoTable(order.getFood(), order.getBeverage(), order.getFood());
        
        outputPanelEmpty.add(table);
        
        this.pack();
        /*
        //Code sourced from stackoverflow to clear table values
        //Source : https://stackoverflow.com/questions/6232355/deleting-all-the-rows-in-a-jtable
        //Remove all rows from the table
        DefaultTableModel dm = (DefaultTableModel)outputOrderTable.getModel();
        int rc = dm.getRowCount();
        for (int i = rc - 1; i >= 0; i--)
            dm.removeRow(i);
        //End borrowed code
        //Add specified row
        String n = ord.getCustomerName();
        String items = ord.getItems();
        dm.addRow(new String[]{n, items});
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        buttonEnterData = new javax.swing.JButton();
        buttonDisplayChoices = new javax.swing.JButton();
        buttonDisplayOrder = new javax.swing.JButton();
        panelContent = new javax.swing.JPanel();
        outputPanelEmpty = new javax.swing.JPanel();
        customerDetails = new prototypeclientserver.ClientCustomer.CustomerDetails();
        menuItems = new prototypeclientserver.ClientCustomer.MenuItems();
        buttonReset = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonEnterData.setText("Enter Data");

        buttonDisplayChoices.setText("Display Choices");

        buttonDisplayOrder.setText("Display Orders");

        panelContent.setLayout(new java.awt.CardLayout());

        outputPanelEmpty.setPreferredSize(new java.awt.Dimension(500, 300));
        outputPanelEmpty.setLayout(new java.awt.BorderLayout());
        panelContent.add(outputPanelEmpty, "card2");

        buttonReset.setText("Reset");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonEnterData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDisplayChoices)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDisplayOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonReset)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelContent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customerDetails, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 591, Short.MAX_VALUE)
                            .addComponent(menuItems, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(6, 6, 6))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuItems, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEnterData)
                    .addComponent(buttonDisplayChoices)
                    .addComponent(buttonDisplayOrder)
                    .addComponent(buttonReset))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientScreenView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientScreenView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientScreenView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientScreenView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientScreenView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDisplayChoices;
    private javax.swing.JButton buttonDisplayOrder;
    private javax.swing.JButton buttonEnterData;
    private javax.swing.JButton buttonReset;
    private prototypeclientserver.ClientCustomer.CustomerDetails customerDetails;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private prototypeclientserver.ClientCustomer.MenuItems menuItems;
    private javax.swing.JPanel outputPanelEmpty;
    private javax.swing.JPanel panelContent;
    // End of variables declaration//GEN-END:variables
}
